version: 1.0.0.{build}

environment:
  packageVersion: 1.0.0
  
configuration: Release

pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

before_build:
- nuget restore
  
after_build:
- ps: nuget pack SimpleFeedReader.nuspec -version "$env:nugetVersion"

artifacts:
- path: '*.nupkg'
  name: nuget-package

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

deploy:
  provider: NuGet
  api_key:
    secure: ZTSMbxq1PJ3ZV6jWoG+AFSMkdqQUxgk8Wx5raFAt9tfNVpcRrhmGkxcjAZXPDA7T
  skip_symbols: false
  artifact: nuget-package
  on:
    branch: master